name: Build debug apk

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout OsmAnd
        uses: actions/checkout@v4
        with:
          path: android

      - name: checkout OsmAnd-resources
        uses: actions/checkout@v4
        with:
          repository: osmandapp/OsmAnd-resources
          path: resources

      - name: checkout OsmAnd-core
        uses: actions/checkout@v4
        with:
          repository: osmandapp/OsmAnd-core
          path: core

      - name: checkout OsmAnd-core-legacy
        uses: actions/checkout@v4
        with:
          repository: osmandapp/OsmAnd-core-legacy
          path: core-legacy

      - name: checkout OsmAnd-build
        uses: actions/checkout@v4
        with:
          repository: osmandapp/OsmAnd-build
          path: build

      - name: checkout OsmAnd-tools
        uses: actions/checkout@v4
        with:
          repository: osmandapp/OsmAnd-tools
          path: tools

      - name: checkout OsmAnd-misc
        uses: actions/checkout@v4
        with:
          repository: osmandapp/OsmAnd-misc
          path: misc

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build with Gradle
        run: |
          cd android
          ./gradlew clean compileNightlyFreeLegacyFatDebugJavaWithJavac assembleNightlyFreeLegacyFatDebug -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m" --no-daemon

      - name: Archive APK
        uses: actions/upload-artifact@v4
        with:
          name: osmand-debug
          path: android/OsmAnd/build/outputs/apk/
